# Generated by Django 4.2.5 on 2024-07-30 11:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deal_app', '0004_model_outlet_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='model_add_fields',
            new_name='Outlet',
        ),
        migrations.RenameModel(
            old_name='model_outlet_details',
            new_name='OutletFields',
        ),
        migrations.RenameModel(
            old_name='register_dealer',
            new_name='RegisterDealer',
        ),
    ]
